config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: "home#register"

get '/', to: "home#home"
get '/home', to: "home#home"


get '/contact', to: "home#contact"
get '/contact/:name', to: "home#contact"
get '/contact/:name/:lastname', to: "home#contact"
get '/contact/:name/show/:id', to: "home#contact"


root to: "tables#index"
resources :tables #resources genera el CRUD, es una palabra reservada

get '/completed', to: "tables#completed"
get '/completed/:id', to: "tables#completed"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if current_user.admin?
      can :manage, :all

    else
      can :create, Table
      can :update, Table
      can :destroy, Table
      can :show, Table
      can :completed, Table
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click.rb
class Click < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :user
  def total_price
    qty.to_f * price.to_f
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tables
  after_create :assign_default_role
  rolify

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/post_controller.rb
class PostController < ApplicationController
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :current, only: [:show, :edit, :update, :destroy]

  def index
    @admin_tables = Table.all
    @tables = current_user.tables.where(completed: false)
  end

  def completed
    @tables = current_user.tables.where(completed: true)
  end


  def new
    @table = Table.new
  end


  def create
    @table = Table.new(table_params)
    if @table.save
      redirect_to tables_path

    else
      render :new, notice: "Error, try again."
    end
  end


  def show
  end


  def edit
  end


  def update
    @table.update(table_params)
    redirect_to tables_path #cambiar luego para path hacia los inventarios
  end



  def destroy
    if @table.completed
      @table.destroy
      redirect_to completed_path
    else
      @table.destroy
      redirect_to tables_path
    end
  end


  private
  def table_params
    params.require(:table).permit(:product, :description, :qty, :price, :total_price, :completed, :user_id)
  end

  def current
    @table = Table.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/table_helper.rb
module TableHelper
end

app/views/home/contact.haml
.body
%h1#cs= 'Customer Support'
%p= 'We are here to help you sort out any problem you may have'
%br/

%p For any inquires contact the email below
%p help@me.com
%p Check the Directory if interested
%br/

.directory
  %h2= "Directory"
  %h5 JD Soteldo
  %p for inquires email: jd@help.com

  %h5 Mickey Chaves
  %p for inquires email: andres210201@gmail.com

  %h5 Omar
  %p for inquires email: omar_dp@outlook.es

.c_links
  = link_to "Go Back", :back
  %br/
  = link_to "Main Menu", "home#home"
  %br/
  - if current_user
    = link_to 'Sign Out', destroy_user_session_path, |
      method: :delete                                |
    %br/
  - else
    = link_to 'Sign In', new_user_session_path
    %br/
    = link_to 'Sign Up', new_user_registration_path
    %br/

app/views/home/home.haml
.body
  %p= "Welcome, #{current_user.name}!"
  %h2#home_title= 'IMS'
%br/
%br/

%h3 What is IMS?
%p.ims_home
  IMS stands for Inventory Managstrongent Syststrong, our goal is to make inventory managstrongent
  as
  %strong
    comfortable easy
  and enjoyable as
  %strong
    possible

.home-links
  = link_to "Check your IMT's", tables_path, class: 'home-links__link'
  = link_to "Contact", contact_path, class: 'home-links__link'
  - if current_user
    = link_to 'Sign Out', destroy_user_session_path,method: :delete, class: 'home-links__link'
  - else
    = link_to 'Sign In', new_user_session_path, class: 'home-links__link'
    = link_to 'Sign Up', new_user_registration_path, class: 'home-links__link'

app/views/home/register.haml
%body.register_body
  %h1.regs Register
%br/
%br/
- if current_user
  = link_to 'Sign Out', destroy_user_session_path, |
    method: :delete                                |
  %br/
- else
  = link_to 'Sign In', new_user_session_path
  %br/
  = link_to 'Sign Up', new_user_registration_path

app/views/layouts/_navbar.haml
-# - unless action_name == "resgiter"
.navigation
  %nav.navigation__nav
    %ul.navigation__list
      %li.navigation__item
        =link_to 'Home', home_path, class: 'navigation__link'
      %li.navigation__item
        =link_to 'IMT', tables_path, class: 'navigation__link'

app/views/layouts/alerts.haml
%p.notice= notice
%p.alert= alert

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title IMS
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    = yield

app/views/tables/_form.haml
= form_for @table do |f|
  = f.label :product
  = f.text_field :product
  = f.label :description
  = f.text_field :description
  = f.label :qty
  = f.number_field :qty
  = f.label :price
  = f.number_field :price, step:"any"
  = f.label :total_price
  = f.number_field :total_price
  = f.hidden_field :user_id, value: current_user.id
  = f.submit
  %br/

app/views/tables/completed.haml
= link_to "Index", tables_path
%br/

= link_to "Main Menu", "home#home"
%br/
%br/

- @tables.each do |table|
  = "Product:"
  = table.product
  %br/

  = "Description:"
  = table.description
  %br/

  = "Quantity:"
  = table.qty
  %br/

  ="Unit Price:"
  = table.price
  ="$"

  %br/

  = "Total Price"
  = table.total_price
  ="$"
  %br/

  = "Completed?"
  = table.completed
  %br/
  = link_to "Show", table_path(table)
  %br
  = link_to "Delete", table_path(table),        |
    method: :delete,                            |
    data: {confirm: 'Sure you want to delete?'} |
  %br

app/views/tables/destroy.haml
%h1
  %u
    %em
      Delete
      %em
  Inventory Management Template :(
= form_for @table do |f|
  = f.label :product
  = f.text_field :product
  = f.label :description
  = f.text_field :description
  = f.label :qty
  = f.number_field :qty
  = f.label :price
  = f.number_field :price
  = f.label :total_price
  = f.number_field :total_price
  = f.submit,                        |
    method: :delete                  |
    data: {confirm: 'Are you sure?'} |
  = link_to "Main Menu", root_path

app/views/tables/edit.haml
%h1 Edit your IMT
= form_for @table do |f|
  = f.label :product
  = f.text_field :product
  = f.label :description
  = f.text_field :description
  = f.label :qty
  = f.number_field :qty
  = f.label :price
  = f.number_field :price, step:"any"
  = f.submit
  = link_to "Go Back", :back
  = link_to "Main Menu", root_path

app/views/tables/index.haml
= link_to "Create", new_table_path
%br
= link_to "Completed IMT", completed_path
%br
= link_to "Main Menu", home_path
%br
%br

%p= "Welcome, #{current_user.name}!"
%br

- if current_user.admin?
  - @admin_tables.each do |table|
    %table.mb-3{:border=>'2'}
      %thead
        %tr
          %th User:
          %th Product:
          %th Description:
          %th Quantity:
          %th Unit Price $
          %th Total Price $
          %th Completed?
      %tbody
        %tr
          %td
          %td= "#{table.product}"
          %td= "#{table.description}"
          %td= "#{table.qty}"
          %td= "#{table.price}"
          %td= "#{table.total_price}"
          %td= "#{table.completed}"
- else
  - @tables.each do |table|
    %table
      %thead
        %tr
          %th Product:
          %th Description:
          %th Quantity:
          %th Unit Price $
          %th Total Price $
          %th Completed?
      %tbody
        %tr
          %td= "#{table.product}"
          %td= "#{table.description}"
          %td= "#{table.qty}"
          %td= "#{table.price}"
          %td= "#{table.total_price}"
          %td= "#{table.completed}"

    = form_for table do |f|
      = f.hidden_field :completed, value: true
      = f.submit "complete", data: { confirm: 'Are you really done?'}
  %br/
  %br/
  %div.index_links
    = link_to "Show IMT", table_path(table)
    %br/
    = link_to 'Update', edit_table_path(table)
    %br/
    = link_to 'Delete', table_path(table), method: :delete, data: { confirm: 'Are you sure?'}

app/views/tables/new.haml
%h3 New IMT!
#input Add More
= render 'tables/form'
= link_to "Go Back", tables_path
= link_to "Main Menu", root_path

app/views/tables/show.haml
%u
  %h2 Insights

%ul#product_table_show
%table{:border=>'2', :width=>'80%'}
  %thead
    %tr
      %th Product:
      %th Description:
      %th Quantity:
      %th Unit Price $
      %th Total Price $
      %th Completed?
  %tbody
    %tr
      %td #{@table.product}
      %td #{@table.description}
      %td #{@table.qty}
      %td #{@table.price}
      %td #{@table.total_price}
      %td #{@table.completed}

  .links
    - if @table.completed
      %br/
      = link_to "Go Back", :back
      %br/
      = link_to "Main Menu", home_path
    - else @table.completed = false
      =link_to "Edit", edit_table_path
      %br
      = link_to "Go Back", :back
      %br
      =link_to "Main Menu", home_path